# Streamlit Configuration for Production Deployment

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

# File upload settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
